---
#database deployment, this is a simple deployment and **NOT** for **PRODUCTION** USE.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: Production
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labesl:
        app: database
    spec:
      containers:
      - image: mysql:8
        name: database
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: database

#default storage class, for volumes please check mysqpl-pv.yml file.
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim